name: Build for Windows

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: docker://lanvas2008/tsmuxer_build:latest
      volumes:
      - /workspace:/github/workspace
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - run: rm -f bin/.gitkeep
      name: clean-bin-folder
      
    - run: ./rebuild_mxe_with_gui.sh
      name: build-for-windows
      
    - uses: actions/upload-artifact@master
      with:
         name: tsMuxer
         path: bin
      name: upload-artefact
